### PR TITLE
Setup actions buildbot, cleanup build scripts

### PR DESCRIPTION
**Pull request by rock3r**
This PR adds a GitHub Actions-based buildbot that we can easily then use to prevent merging PRs which fail tests or other checks. Ideally this could also replace Travis entirely (it tends to be faster, anyway).

Note that currently `master` has some compilation issues, which should be fixed when one of the other pending PRs is merged, so maybe it's too early to enable protected branches yet. But we can start, at least.

This PR also fills in the blanks, and updates, the `README` file, and updates the LICENSE notice with the current year, and replaces @mpgirro's name with "the Wien contributors" so as to cover my contributions as well :)

Lastly, there's some cleanup of the `build.gradle.kts` file, removing some stuff we don't need anymore.

### CODE REVIEW

**Comment by mpgirro** [comment]
After all those huge PRs the large few days, I rather enjoy these small ones. It's much easier to have a look at them. Keep 'em coming 😄

**Comment by rock3r** [comment]
@mpgirro yeah I know, had a bunch of small pieces to move around and big features to implement... but it should be mostly done now. I am still going to do these:

 1. Add support for `podcast:` namespace (mid-size PR, likely, needs both parsing & writing, plus tests)
 2. Ensure parsers read empty fields as null (should actually already mostly be done, I may add some tests to codify it better)
 3. Ensure writers don't write out empty fields/attributes (shouldn't be much work, but tests may be a lot)
 4. Add parsing/writing of RSS `<categories>` nodes in `<channel>` (shouldn't be much work)
 5. Add some end-to-end tests that read a bunch of real-life RSS feeds, write them back to disk, parse them back up and compare the `Podcast` between the first and second parse — I expect this can bring up a bunch of bugs. No real need for business logic test, but there will be a ton of test resources and code

**Comment by mpgirro** [comment]
@rock3r thanks for the roadmap update. I am wondering about the real-life RSS feed tests. How do you plan to fetch the feeds? Back when I started the project, I excluded the actual fetching of a feed from Wien's API, and left it to the client. I did not want to "bloat" the library with it. How are your thoughts on that?

**Comment by rock3r** [comment]
Oh in this case I'd embed them in test resources. I want to keep the
networking out of this as well, don't worry :)

>

**Comment by mpgirro** [comment]
I am fine with switching to GitHub actions (I have so far not used it yet, but am quite curious to give it a try) and retiring the Travis setup. It is causing troubles currently anyway. And as you mentioned, the speed isn't satisfying either.

**Pull request merged**
