### PR TITLE
Tweak APIs, reorganize code

### PR DESCRIPTION
**Pull request by rock3r**
This PR mostly does some minor tweaks to some internal APIs, by changing a couple of method signatures to make them more idiomatic, and reorganizes some code. In particular, the DOM-related extensions, utils and helpers are now grouped in the `io.hemin.wien.dom` package. No behaviour changes.

### CODE REVIEW

**Comment by rock3r** [comment]
Not sure why Travis is failing: the tests do run just fine on my machine. Maybe it's because it's using Java 8?

**Comment by rock3r** [comment]
Actually, I'm sure that's the issue:

image

Let me see if I can edit the Travis build to get it to work...

**Comment by rock3r** [comment]
Damn Travis is SLOW

**Comment by rock3r** [comment]
Seems like now Travis is failing because, essentially, __whatever__. It failed to send coverage data to coveralls. Ugh.

**Comment by mpgirro** [comment]
Those external services are starting to become a nuisance rather than a relieve...

**Comment by rock3r** [comment]
I stopped using Travis a long time ago, for that exact reason. I'm a bit sad to see it's not improved much :(

**Comment by mpgirro** [comment]
Then let's get rid of it. I'm interested to see what GitHub actions can do :)

**Pull request merged**
